trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Sonar_SAST_Scan_Job
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - script: |
      mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=AzureDevOpsOrganization -Dsonar.projectKey=azuredevopsorganizationprojectkey -Dsonar.token=2db84745a0916f2469b892ace61c610893b543f0
    displayName: "Integrate SAST using SonarCloud to populate code coverage and secure pipeline variable in Azure DevOps DevSecOps Pipeline"

